name 'tomcat'
maintainer 'Saikrishna Mandava'
maintainer_email 'saikrishna.mandava@yahoo.com'
license 'all_rights'
description 'Installs/Configures tomcat'
long_description 'Installs/Configures tomcat'
version '0.1.0'
